# Extend from the base image built by the main Dockerfile
ARG BASE_IMAGE
FROM ${BASE_IMAGE}

WORKDIR /

# Install development tools and dependencies
RUN apt-get install -y \
    # build dependencies
    ninja-build \
    gettext \
    cmake \
    curl \
    build-essential 


# cloning repo, then getting stable version
RUN git clone https://github.com/neovim/neovim
WORKDIR /neovim
RUN git checkout stable

RUN make CMAKE_BUILD_TYPE=RelWithDebInfo
RUN make install

WORKDIR /app